### ISSUE TITLE
Funding request: add SSI event to Category

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#273]

**Comment by rgaiacs** [comment]
[Currently fund categories are](https://github.com/softwaresaved/lowfat/blob/master/lowfat/models.py#L27)

- Attending a conference/workshop;
- Organising a conference/workshop (e.g. Software Carpentry);
- Policy related event; and
- Other.

The new category is intended for Fellows Selection Day, Fellows Inaugural Day, Collaborations Workshop, ...?

**Comment by gperu** [comment]
Yes, correct. For all events mandated from SSI, which will be charged to core funds and not to the personal grant.

**Comment by gperu** [comment]
A tick-box saying "Is this related with Fellows face to face selection meeting, Fellows inaugural meeting or Collaborations Workshop?" has been implemented.

Is there a reason why we can't simply have a 5th choice in the menu "SSI event"?

**Comment by rgaiacs** [comment]
> Is there a reason why we can't simply have a 5th choice in the menu "SSI event"?

"SSI event" is quite general. I'm thinking a little in terms of metrics and would be great to say "we sponsored X people to attend X events and Y people to organise Y event".

**Comment by rgaiacs** [comment]
What is implemented now is

![img_20170419_145557](https://cloud.githubusercontent.com/assets/1506457/25184296/f316f91e-2511-11e7-96cb-439c3015126d.jpg)

Every funding request has a [`mandatory` field](https://github.com/softwaresaved/lowfat/blob/master/lowfat/models.py#L356) that will [(1)](https://github.com/softwaresaved/lowfat/blob/master/lowfat/models.py#L618) set expense claim's `funds_from` to be "core", [(2)](https://github.com/softwaresaved/lowfat/blob/master/lowfat/models.py#L307) remove from committed and [(3)](https://github.com/softwaresaved/lowfat/blob/master/lowfat/models.py#L325).

Later changes on `mandatory` will effect (2) and (3) **but not** (1).

# Why not "SSI event" to Category

To help us with metrics. "SSI event" doesn't tell us if was attend of organise something.

# Why duplicated `funds_from`

[Funding request has `funds_from_default`](https://github.com/softwaresaved/lowfat/blob/master/lowfat/models.py#L431) and [expense claim has `funds_from`](https://github.com/softwaresaved/lowfat/blob/master/lowfat/models.py#L590). This "duplication" enable us to have a fine control of which pot the money is coming from. The same for `grant_used`.

# Possible improvement

Use `funds_from` instead of `mandatory` when sort finances.
