### ISSUE TITLE
Add Fellow name to Funding request in drop-down menu

### ISSUE THREAD

**Issue by gperu** [softwaresaved/lowfat#383]
This is important because when the administrator submits a funding request, in the several cases of Funding requests with the same name, has to go to Django admin in order to check the number of the Funding request and find the right one.

**Comment by rgaiacs** [comment]
This is a user experience (UX) that I'm happy to review.

# For admins

## Using fund request page

If you go to the fund request page of interest.

![screencapture-localhost-8000-request-6-1503663736189](https://user-images.githubusercontent.com/1506457/29713881-93c37046-8998-11e7-9b1d-2ff5d736e69d.png)

You will find a button to create a new expense. That button will filter the fund request drop-down menu to only one option.

![screencapture-localhost-8000-expense-1503663752762](https://user-images.githubusercontent.com/1506457/29713908-ae8c627a-8998-11e7-865d-e67ca64babad.png)

## Otherwise

The drop down menu will have **all** approved open funding requests.

# For fellows

## Using fund request page

See behaviour for admins.

## Otherwise

The drop down menu will have **only** approved open funding requests by that fellow.

# More details

The [`__str__` function](https://github.com/softwaresaved/lowfat/blob/master/lowfat/models.py#L493) is used to generate the text at the drop-down menu. This function is used in other places and I want to not change it.

**Comment by rgaiacs** [comment]
0d883cb has some improvements. I'm closing this for now.
