### ISSUE TITLE
Provide example of how much money is left

### ISSUE THREAD

**Issue by rgaiacs** [softwaresaved/lowfat#507]
https://softwaresaved.github.io/lowfat/claimant/money.html should now have a example of how money left is calculated.

![screenshot from 2018-11-14 14-36-39](https://user-images.githubusercontent.com/1506457/48489376-d1b69e00-e81a-11e8-9989-fa376aa8210d.png)

@gperu The text need review.

**Comment by yochannah** [comment]
I like this! One note is the colours: maybe make the red into grey? Red symbolises warning/bad to me, and spending the fellowship money isn't really bad as such ;) It would also help skirt any red/green colourblind issues that way. 

I also might turn the text over the green to white coloured text with a black shadow.

**Comment by agbeltran** [comment]
I think this would be a nice feature and I agree with the points above about considering accessibility issues. 

Another functionality for this visualization that I think would be useful is the possibility of hover over the different bars and be able to see to what funding request it corresponds to. Also, it would be great to be able to click on the bars so that the corresponding funding request is loaded.

Thanks for thinking on this to make it easier for fellows to check their funding!

**Comment by yochannah** [comment]
+1 for the hover and click suggestions. Nice way to provide the same functionality for both touch and mouse.

**Comment by rgaiacs** [comment]
Thanks for feedback. I'm closing this as #531 implements part of it.

> Another functionality for this visualization that I think would be useful is the possibility of hover over the different bars and be able to see to what funding request it corresponds to. Also, it would be great to be able to click on the bars so that the corresponding funding request is loaded.

We will review it in the future and might implement the extra features.
