### ISSUE TITLE
Ensure that a claimant account can't be created with no email address

### ISSUE THREAD

**Issue by jag1g13** [softwaresaved/lowfat#630]
We think the recent errors with password reset emails were due to missing email addresses

**Comment by rainsworth** [comment]
Note that this is for User accounts (vs claimant accounts).

**Comment by phillybroadbent** [comment]
Re-registered the user model to the admin panel with email defined in the fieldsets. In order to make the EmailField a required field, we created a custom class which depreciated the original email and replaced it with a required email field. Then, we updated add_form from UserAdmin with the custom MyUserCreationForm. 

The correct way to do this is to use a custom user model however this must be set up before the site is first deployed. As we can now not introduce a custom user model we have included some documentation in settings.py to signpost future development.
