### ISSUE TITLE
Figure 4a sort options

### ISSUE THREAD

**Issue by SimonHettrick** [softwaresaved/lowfat#713]
Reorder the data so that the the bar stacks up with junior RSEs on the left, std RSEs in the middle and senior RSEs on the right.

Sort the data to produce two charts:

1. The data sorted with the group with the most std RSEs at the top and the least std RSEs at bottom
2. The data sorted so that the biggest group overall is at the top and the smallest group overall is at the bottom.

**Comment by robertn01** [comment]
I've created the following plots (also sent a PM on Slack).

![Image](https://user-images.githubusercontent.com/36110768/234954629-64acf6c4-4db5-472e-b55e-43f034830dfe.png)
![Image](https://user-images.githubusercontent.com/36110768/234954627-abedf494-dcd6-44ed-8913-ce79d989c299.png)
![Image](https://user-images.githubusercontent.com/36110768/234954628-002cdf05-23ef-45b7-bf58-ffac8da0488c.png)
![Image](https://user-images.githubusercontent.com/36110768/234954630-3bbe2d51-1a43-4db1-b614-5b7f58cb77b4.png)

**Comment by robertn01** [comment]
Only 14 groups were included in the previous sketch visualisations due to a filtering step where all records from the data frame removed where the number of calculated junior RSE staff was zero (either '0' or missing responses). Now, removed this filter. Re-generated 100% plots look like as can be seen on the attachments. Such filter made sense for a univariate plot where sole jr stuff numbers are presented for which case we've agreed to 'just remove zero/ NA jr staff nr rows.

![Image](https://user-images.githubusercontent.com/36110768/235280615-7cec876b-9487-41fc-a0ee-7b07858864c1.png)
![Image](https://user-images.githubusercontent.com/36110768/235280616-276a337a-13bc-4db4-9333-7b6f54f453c5.png)
![Image](https://user-images.githubusercontent.com/36110768/235280617-68b89ac9-8013-4578-925a-7191abfe222a.png)
